config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :companies do
    resources :cash_managements, except: [:index, :show]
  end
  resources :users, only: [:edit, :update]
  root 'companies#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cash_management.rb
# frozen_string_literal: true

class CashManagement < ApplicationRecord
  monetize :cash_in_cents, numericality: { greater_than: 0 }
  monetize :cash_out_cents, numericality: { greater_than: 0 }

  belongs_to :company

  validates :cash_in_cents, :cash_out_cents, :year, :month, :company, presence: true
  validates_uniqueness_of :company_id, scope: %i[month year]
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  monetize :initial_cash_cents, numericality: { greater_than: 0 }

  has_many :cash_managements, dependent: :delete_all
  belongs_to :user

  validates :initial_cash_cents, :name, :country, presence: true

  def country_name
    country = ISO3166::Country[self.country]
    country.translations[I18n.locale.to_s] || country.name
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  enum role: { student: 0, teacher: 1 }
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :companies, dependent: :delete_all

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_additional_parameters, if: :devise_controller?

  protected

  def configure_additional_parameters
    additional_params = %i[role first_name last_name]
    devise_parameter_sanitizer.permit(:sign_up, keys: additional_params)
  end

  private

  def auth_student!
    raise I18n.t('authorize_error') unless current_user.student?
  end
end

app/controllers/cash_managements_controller.rb
# frozen_string_literal: true

class CashManagementsController < ApplicationController
  before_action :find_company, only: %i[new edit create update destroy]
  before_action :find_cash_management, only: %i[edit update destroy]
  before_action :auth_student!, only: %i[create update destroy]

  def new
    @cash_management = @company.cash_managements.new
  end

  def edit; end

  def create
    @cash_management = @company.cash_managements.new(cash_params)

    if @cash_management.save
      redirect_to @company
    else
      render 'new'
    end
  end

  def update
    if @cash_management.update(cash_params)
      redirect_to @company
    else
      render 'edit'
    end
  end

  def destroy
    @cash_management.destroy

    redirect_to @company
  end

  private

  def cash_params
    permit_params = params.require(:cash_management).permit(:month, :cash_in, :cash_out)
    month_params = permit_params.delete(:month).split(' ')
    permit_params.merge({ month: month_params.first, year: month_params.last })
  end

  def find_cash_management
    @cash_management = @company.cash_managements.find(params[:id])
  end

  def find_company
    @company = Company.find(params[:company_id])
  end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  before_action :find_company, only: %i[show edit update destroy]
  before_action :auth_student!, only: %i[create update destroy]

  def index
    @companies = current_user.student? ? current_user.companies : Company.all
  end

  def new
    @company = current_user.companies.new
  end

  def edit; end

  def create
    @company = current_user.companies.new(company_params)

    if @company.save
      redirect_to companies_path
    else
      render 'new'
    end
  end

  def update
    if @company.update(company_params)
      redirect_to companies_path
    else
      render 'edit'
    end
  end

  def destroy
    @company.destroy

    redirect_to companies_path
  end

  private

  def company_params
    params.require(:company).permit(:name, :country, :initial_cash)
  end

  def find_company
    @company = Company.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to companies_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def months_for_company(company)
    date = company.created_at.to_date
    months = []
    (0..23).each do |m|
      month_value = date.next_month(m).strftime('%B %Y')
      months << [month_value, month_value]
    end
    months
  end
end

app/views/cash_managements/_form.html.haml
%p= link_to 'Back', company_path(@company), class: 'btn btn-info'

= form_for [@company, @cash_management], class: 'form-group' do |f|
  .field.form-group
    = f.label :month, class: 'col-form-label'
    = f.select :month, options_for_select(months_for_company(@company)), {}, class: 'form-control'

  .field.form-group
    = f.label :cash_in, class: 'col-form-label'
    = f.number_field :cash_in, class: 'form-text form-control'

  .field.form-group
    = f.label :cash_out, class: 'col-form-label'
    = f.number_field :cash_out, class: 'form-text form-control'

  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/cash_managements/edit.html.haml
.container
  %h1 Edit new cash info

  = render 'form'

app/views/cash_managements/new.html.haml
.container
  %h1 Create new cash info

  = render 'form'

app/views/companies/_form.html.haml
%p= link_to 'Back', companies_path, class: 'btn btn-info'

= form_for @company, class: 'form-group' do |f|
  .field.form-group
    = f.label :name, class: 'col-form-label'
    = f.text_field :name, class: 'form-text form-control'

  .field.form-group
    = f.label :initial_cash, class: 'col-form-label'
    = f.number_field :initial_cash, class: 'form-text form-control'

  .field.form-group
    = f.label :country_code, class: 'col-form-label'
    = f.country_select :country, {priority: %w(US CA)}, prompt: 'Please select a country', class: 'form-control'

  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/companies/edit.html.haml
.container
  %h1 Edit company

  = render 'form'

app/views/companies/index.html.haml
.container
  %h1.page-header Listing your companies
  = link_to 'Update user detail', edit_user_path(current_user), class: 'btn btn-info'
  - if current_user.student?
    = link_to 'Create company', new_company_path, class: 'btn btn-info'
  .row
    %table.table
      %thead
        %tr
          %th{scope: 'col'} #
          %th{scope: 'col'} Name
          %th{scope: 'col'} Country
          %th{scope: 'col'}
          %th{scope: 'col'}
      %tbody
        - @companies.each_with_index do |company, index|
          %tr
            %th{scope: 'row'}= index + 1
            %th= link_to "#{company.name}", company_path(company)
            %th= company.country_name
            - if current_user.student?
              %th= link_to 'Update', edit_company_path(company), class: 'btn btn-success'
              %th= link_to 'Delete', company_path(company), method: :delete, class: 'btn btn-danger'

app/views/companies/new.html.haml
.container
  %h1 Create company

  = render 'form'

app/views/companies/show.html.haml
.container
  %h2= "Company name: #{@company.name}"
  %p= "Country: #{@company.country_name}"
  %p= "Initial cash: #{@company.initial_cash}"
  %p= "Student: #{@company.user.full_name}"

  %p= link_to 'Add new cash info', new_company_cash_management_path(@company), class: 'btn btn-info'
  %p= link_to 'Back', companies_path, class: 'btn btn-info'

  .row
    %table.table
      %thead
        %tr
          %th{scope: 'col'} Year
          %th{scope: 'col'} Month
          %th{scope: 'col'} Cash in
          %th{scope: 'col'} Cash out
          %th{scope: 'col'}
          %th{scope: 'col'}
      %tbody
        - @company.cash_managements.each do |cash|
          %tr
            %th{scope: 'row'}= cash.year
            %th= cash.month
            %th= cash.cash_in
            %th= cash.cash_out
            - if current_user.student?
              %th= link_to 'Update', edit_company_cash_management_path(@company, cash), class: 'btn btn-success'
              %th= link_to 'Delete', company_cash_management_path(@company, cash), method: :delete,
              class: 'btn btn-danger'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%- if current_user %>
      <nav class="navbar navbar-light bg-light">
        <%= button_to 'Log out', destroy_user_session_path, method: 'delete', class: 'btn' %>
      </nav>
    <% end %>
    <p class="alert-primary"><%= notice %></p>
    <p class="alert-danger"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.haml
%p= link_to 'Back', companies_path, class: 'btn btn-info'

= form_for current_user, class: 'form-group' do |f|
  .field.form-group
    = f.label :first_name, class: 'col-form-label'
    = f.text_field :first_name, class: 'form-text form-control'

  .field.form-group
    = f.label :last_name, class: 'col-form-label'
    = f.text_field :last_name, class: 'form-text form-control'

  .field.form-group
    = f.label :email, class: 'col-form-label'
    = f.text_field :email, class: 'form-text form-control'

  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/users/edit.html.haml
.container
  %h1 Edit user info

  = render 'form'